package vista;

import datos.GuardarBitacora;
import datos.TrasladoProductoDAO;
import dominio.ProcesosRepetidos;
import dominio.TrasladoProducto;
import java.awt.Color;
import java.time.LocalDateTime;
import java.util.List;

/**
 *
 * @author Jeff
 */
public class Prcs_TrasladoProducto extends javax.swing.JInternalFrame {

    ProcesosRepetidos prcs_repetidos = new ProcesosRepetidos();
    TrasladoProducto pisos = new TrasladoProducto();
    GuardarBitacora bitacora = new GuardarBitacora();

    public Prcs_TrasladoProducto() {
        initComponents();
        diseño();
        actualizarTabla("");
    }

    public void diseño() {
        this.setTitle("Mantenimiento de Unidad");
        Txt_buscar.setBorder(null);
        Txt_buscar1.setBorder(null);
        Txt_buscar2.setBorder(null);
        Txt_buscar3.setBorder(null);
        Txt_buscar4.setBorder(null);
        prcs_repetidos.Cursor(Btn_buscar, Btn_ingresar);
    }

    public void actualizarTabla(String codigo) {
        ProcesosRepetidos prcs_repetidos = new ProcesosRepetidos();
        TrasladoProductoDAO.codigoAuxiliar = codigo;
        TrasladoProductoDAO.nombreAuxiliar = codigo;
        String columnas[] = {"ID", "PRODUCTO", "BODEGA", "CANTIDAD", "FECHA", "HORA", "DESTINO", "ESTADO"};
        int cantidadcolumnas = columnas.length;
        prcs_repetidos.llenarColumnas(columnas, cantidadcolumnas, Tbl_Datos);
        String datos[] = new String[cantidadcolumnas];
        int tamaño[] = {75, 75, 75, 100, 75, 100, 100, 75};
        TrasladoProductoDAO pisosdao = new TrasladoProductoDAO();
        List<TrasladoProducto> piso = pisosdao.select();
        for (TrasladoProducto listaServicio : piso) {
            datos[0] = String.valueOf(listaServicio.getCodigo());
            datos[1] = String.valueOf(listaServicio.getCodigoProducto());
            datos[2] = String.valueOf(listaServicio.getCodigoBodega());
            datos[3] = String.valueOf(listaServicio.getCantidadProducto());
            datos[4] = String.valueOf(listaServicio.getFechaSalida());
            datos[5] = String.valueOf(listaServicio.getHoraSalida());
            datos[6] = String.valueOf(listaServicio.getBodegaDestino());
            if (String.valueOf(listaServicio.getEstado()).equals("1")) {
                datos[7] = "Activo";
            } else {
                datos[7] = "Inactivo";
            }
            prcs_repetidos.llenarFilas(datos, tamaño, Tbl_Datos);
        }
    }

//    public void fechaActual() {
//        LocalDateTime locaDate = LocalDateTime.now();
//        int anio = locaDate.getYear();
//        int mes = locaDate.getMonthValue();
//        int dia = locaDate.getDayOfMonth();
//        fechaOrden = String.valueOf(anio + "-" + mes + "-" + dia);
//    }
//    public void horaActual() {
//        LocalDateTime locaDate = LocalDateTime.now();
//        int horas = locaDate.getHour();
//        int minutos = locaDate.getMinute();
//        int segundos = locaDate.getSecond();
//        horaOrden = String.valueOf(horas + ":" + minutos + ":" + segundos);
//    }
    public void Limpiar() {
        prcs_repetidos.Limpiar(Txt_buscar, Txt_buscar1, Txt_buscar2, Txt_buscar3, Txt_buscar4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGp_tipo = new javax.swing.ButtonGroup();
        BtnGp_estado = new javax.swing.ButtonGroup();
        Pnl_datos = new javax.swing.JPanel();
        Lbl_codigoNombre = new javax.swing.JLabel();
        Txt_buscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();
        Btn_fondo_buscar = new javax.swing.JPanel();
        Btn_buscar = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Lbl_codigoNombre1 = new javax.swing.JLabel();
        Txt_buscar1 = new javax.swing.JTextField();
        Lbl_codigoNombre2 = new javax.swing.JLabel();
        Txt_buscar2 = new javax.swing.JTextField();
        Lbl_codigoNombre3 = new javax.swing.JLabel();
        Lbl_codigoNombre4 = new javax.swing.JLabel();
        Lbl_codigoNombre5 = new javax.swing.JLabel();
        Txt_buscar3 = new javax.swing.JTextField();
        Txt_buscar4 = new javax.swing.JTextField();
        Btn_fondo_buscar1 = new javax.swing.JPanel();
        Btn_ingresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        Pnl_datos.setBackground(new java.awt.Color(36, 47, 65));
        Pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        Lbl_codigoNombre.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre.setText("Código:");

        Txt_buscar.setBackground(new java.awt.Color(36, 47, 65));
        Txt_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Txt_buscar.setForeground(new java.awt.Color(255, 255, 255));
        Txt_buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tbl_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_DatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbl_Datos);

        Btn_fondo_buscar.setBackground(new java.awt.Color(97, 212, 195));

        Btn_buscar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn_buscar.setText("Buscar");
        Btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_buscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_buscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Btn_fondo_buscarLayout = new javax.swing.GroupLayout(Btn_fondo_buscar);
        Btn_fondo_buscar.setLayout(Btn_fondo_buscarLayout);
        Btn_fondo_buscarLayout.setHorizontalGroup(
            Btn_fondo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        Btn_fondo_buscarLayout.setVerticalGroup(
            Btn_fondo_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Btn_fondo_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        Lbl_codigoNombre1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre1.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre1.setText("De:");

        Txt_buscar1.setBackground(new java.awt.Color(36, 47, 65));
        Txt_buscar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Txt_buscar1.setForeground(new java.awt.Color(255, 255, 255));
        Txt_buscar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Lbl_codigoNombre2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre2.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre2.setText("Hacia:");

        Txt_buscar2.setBackground(new java.awt.Color(36, 47, 65));
        Txt_buscar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Txt_buscar2.setForeground(new java.awt.Color(255, 255, 255));
        Txt_buscar2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Lbl_codigoNombre3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre3.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre3.setText("Bodega");

        Lbl_codigoNombre4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre4.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre4.setText("Producto:");

        Lbl_codigoNombre5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Lbl_codigoNombre5.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_codigoNombre5.setText("Cantidad:");

        Txt_buscar3.setBackground(new java.awt.Color(36, 47, 65));
        Txt_buscar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Txt_buscar3.setForeground(new java.awt.Color(255, 255, 255));
        Txt_buscar3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Txt_buscar4.setBackground(new java.awt.Color(36, 47, 65));
        Txt_buscar4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Txt_buscar4.setForeground(new java.awt.Color(255, 255, 255));
        Txt_buscar4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Btn_fondo_buscar1.setBackground(new java.awt.Color(97, 212, 195));

        Btn_ingresar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Btn_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn_ingresar.setText("Confirmar");
        Btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_ingresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Btn_fondo_buscar1Layout = new javax.swing.GroupLayout(Btn_fondo_buscar1);
        Btn_fondo_buscar1.setLayout(Btn_fondo_buscar1Layout);
        Btn_fondo_buscar1Layout.setHorizontalGroup(
            Btn_fondo_buscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Btn_fondo_buscar1Layout.setVerticalGroup(
            Btn_fondo_buscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Btn_ingresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pnl_datosLayout = new javax.swing.GroupLayout(Pnl_datos);
        Pnl_datos.setLayout(Pnl_datosLayout);
        Pnl_datosLayout.setHorizontalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datosLayout.createSequentialGroup()
                                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lbl_codigoNombre)
                                    .addComponent(Lbl_codigoNombre3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7)
                                    .addComponent(Txt_buscar)
                                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                                        .addComponent(Lbl_codigoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lbl_codigoNombre2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Txt_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                        .addComponent(Lbl_codigoNombre4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lbl_codigoNombre5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(Btn_fondo_buscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_fondo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_datosLayout.setVerticalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_fondo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Txt_buscar)
                                .addComponent(Lbl_codigoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_codigoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_buscar1)
                        .addComponent(Lbl_codigoNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_codigoNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_buscar2))
                    .addComponent(Txt_buscar3)
                    .addComponent(Lbl_codigoNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_codigoNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txt_buscar4)))
                .addGap(18, 18, 18)
                .addComponent(Btn_fondo_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_buscarMouseEntered
        Btn_fondo_buscar.setBackground(new Color(114, 243, 227));
    }//GEN-LAST:event_Btn_buscarMouseEntered

    private void Btn_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_buscarMouseExited
        Btn_fondo_buscar.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_Btn_buscarMouseExited

    private void Tbl_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_DatosMouseClicked
//        if (evt.getClickCount() == 2) {
//            jLabel1.setText(Tbl_Datos.getValueAt(Tbl_Datos.getSelectedRow(), 0).toString());
//            txtnombre.setText(Tbl_Datos.getValueAt(Tbl_Datos.getSelectedRow(), 1).toString());
//            txtnombre1.setText(Tbl_Datos.getValueAt(Tbl_Datos.getSelectedRow(), 2).toString());
//            if (Tbl_Datos.getValueAt(Tbl_Datos.getSelectedRow(), 3).toString().equals("Activo")) {
//                Rdb_Activo.setSelected(true);
//            } else {
//                Rdb_Inactivo.setSelected(true);
//            }
//            bitacora.GuardarEnBitacora("Buscar", "2004");
//        }
    }//GEN-LAST:event_Tbl_DatosMouseClicked

    private void Btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_buscarMouseClicked
        actualizarTabla(Txt_buscar.getText());
    }//GEN-LAST:event_Btn_buscarMouseClicked

    private void Btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseClicked
        if (prcs_repetidos.isNoneEmpty(Txt_buscar1, Txt_buscar2, Txt_buscar3, Txt_buscar4)) {
            TrasladoProductoDAO pisosdao = new TrasladoProductoDAO();
            LocalDateTime locaDate = LocalDateTime.now();
            int anio = locaDate.getYear();
            int mes = locaDate.getMonthValue();
            int dia = locaDate.getDayOfMonth();
            String fechaOrden = String.valueOf(anio + "-" + mes + "-" + dia);
            
            int horas = locaDate.getHour();
            int minutos = locaDate.getMinute();
            int segundos = locaDate.getSecond();
            String horaOrden = String.valueOf(horas + ":" + minutos + ":" + segundos);

            pisos.setCodigoProducto(Txt_buscar4.getText());
            pisos.setCodigoBodega(Txt_buscar1.getText());
            pisos.setCantidadProducto(Txt_buscar3.getText());
            pisos.setFechaSalida(fechaOrden);
            pisos.setHoraSalida(horaOrden);
            pisos.setEstado("1");
            pisos.setBodegaDestino(Txt_buscar2.getText());
            pisosdao.insert(pisos);
            actualizarTabla("");
            prcs_repetidos.AlertaMensaje("guardado", "Traslado", "exitosamente");
            Limpiar();
            bitacora.GuardarEnBitacora("Guardar", "2004");
        } else {
        }
    }//GEN-LAST:event_Btn_ingresarMouseClicked

    private void Btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ingresarMouseEntered

    private void Btn_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ingresarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ingresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGp_estado;
    private javax.swing.ButtonGroup BtnGp_tipo;
    private javax.swing.JLabel Btn_buscar;
    private javax.swing.JPanel Btn_fondo_buscar;
    private javax.swing.JPanel Btn_fondo_buscar1;
    private javax.swing.JLabel Btn_ingresar;
    private javax.swing.JLabel Lbl_codigoNombre;
    private javax.swing.JLabel Lbl_codigoNombre1;
    private javax.swing.JLabel Lbl_codigoNombre2;
    private javax.swing.JLabel Lbl_codigoNombre3;
    private javax.swing.JLabel Lbl_codigoNombre4;
    private javax.swing.JLabel Lbl_codigoNombre5;
    private javax.swing.JPanel Pnl_datos;
    private javax.swing.JTable Tbl_Datos;
    private javax.swing.JTextField Txt_buscar;
    private javax.swing.JTextField Txt_buscar1;
    private javax.swing.JTextField Txt_buscar2;
    private javax.swing.JTextField Txt_buscar3;
    private javax.swing.JTextField Txt_buscar4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
